### ISSUE TITLE
多页面的streamlit应用，可以实现订阅信息的同步么

### ISSUE THREAD

**Issue by ningshenlo** [mthli/lemonsqueepy#1]

**Comment by mthli** [comment]
@ningshenlo  没用过 [streamlit](https://github.com/streamlit/streamlit)，不过应该与 streamlit 无关。

[根据项目 API 文档](https://github.com/mthli/lemonsqueepy/wiki/Tutorial-(Chinese)#apis)，所有 API 都是需要 App 主动去请求的，所以你可能要在多页面里写一些定时轮询的逻辑（或者其他可以在多页面间同步信息的机制）。

**Comment by ningshenlo** [comment]
好的，明白了，我再研究研究streamlit
