### ISSUE TITLE
支持一些自定义消费模型的定义与校验吗？

### ISSUE THREAD

**Issue by ivanberry** [mthli/lemonsqueepy#2]
比如，我某一个产品一个计费周期里只能使用N次，N次使用后，认为不可再使用。

是不是在商店定义的商品属性里有，但是需要自己来处理次数消耗的逻辑？

**Comment by mthli** [comment]
> 比如，我某一个产品一个计费周期里只能使用N次，N次使用后，认为不可再使用。
> 
> 是不是在商店定义的商品属性里有，但是需要自己来处理次数消耗的逻辑？

@ivanberry 看起来 Lemon Squeezy 并没有（很好地）支持这种 N 次使用后过期的机制。Lemon 只是帮你解决了判断「这个用户有没有付费」的问题，剩下这个用户可以使用多少次，还是需要在你自己的后端代码里实现。

有一种变通的方法是使用 License，因为 License 可以同时指定激活次数和计费周期。但是每次激活 License 都要去请求 Lemon API，会比较慢，所以不推荐这样使用。

**Comment by ivanberry** [comment]
感谢回复
