### ISSUE TITLE
Activate your store

### ISSUE THREAD

**Issue by jimvvv** [mthli/lemonsqueepy#6]
你好，

请问在lemonsqueezy中创建商店需要注意点什么吗？
比如Business / Home address，这些字段需要用外国或者香港地址么，还是随便都可以？

感谢！

**Comment by mthli** [comment]
> 你好，
> 
> 请问在lemonsqueezy中创建商店需要注意点什么吗？ 比如Business / Home address，这些字段需要用外国或者香港地址么，还是随便都可以？
> 
> 感谢！

@kzkz221 最好和你的收款银行卡（Payout）在同一个地区吧，Lemon Squeezy 现在不支持大陆出金（但支持大陆收款），所以你如果是香港卡就建议填写香港的地址。填大陆的地址可能也可以，但是我没试过。
